name: Test cache-debs action

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./cache-debs
      - run: |
          sudo apt-get update
          sudo apt-get --yes install python3-full
